apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-devops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/TU_USUARIO/proyecto-devops.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true      # limpia recursos que ya no están en el repo
      selfHeal: true   # repara desalineaciones automáticamente
    syncOptions:
      - CreateNamespace=true
