apiVersion: v1
kind: Secret
metadata:
  name: launchdarkly-secret
type: Opaque
data:
  sdk-key: TU_SDK_KEY_EN_BASE64   # <-- aquÃ­ va tu SDK Key de LaunchDarkly en base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-devops
  labels:
    app: api-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-devops
  template:
    metadata:
      labels:
        app: api-devops
    spec:
      containers:
        - name: api-devops
          image: josuelozada/api-devops:latest   # <-- tu usuario Docker Hub
          ports:
            - containerPort: 8000
          env:
            - name: LAUNCHDARKLY_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: launchdarkly-secret
                  key: sdk-key
---
apiVersion: v1
kind: Service
metadata:
  name: api-devops-svc
spec:
  selector:
    app: api-devops
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
