apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-devops
  labels:
    app: api-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-devops
  template:
    metadata:
      labels:
        app: api-devops
    spec:
      containers:
        - name: api-devops
          image: josuelozada/api-devops:latest   # imagen que publica tu pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: LAUNCHDARKLY_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: launchdarkly-secret
                  key: sdk-key
---
apiVersion: v1
kind: Secret
metadata:
  name: launchdarkly-secret
type: Opaque
data:
  # SDK key real de LaunchDarkly (entorno Test), codificada en Base64
  # sdk-cacf51c7-c046-498e-a9fa-0d2209ed43fc
  sdk-key: c2RrLWNhY2Y1MWM3LWMwNDYtNDk4ZS1hOWZhLTBkMjIwOWVkNDNmYw==
